version: '3'
services: 
  test:
    container_name: wasm_app
    build: 
      context: ./app/
    restart: always
    ports:
      - "7777:7777"
    healthcheck:
      test: ["CMD", "socat", "TCP4:localhost:7777", "-"]
      interval: 57s
      timeout: 3s
      retries: 1
